export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRY_DETAIL = "GET_COUNTRY_DETAIL";
export const CURRENT_PAGE = "CURRENT_PAGE";
export const PREVIUS_PAGE = "PREVIUS_PAGE";
export const NEXT_PAGE = "NEXT_PAGE";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const CREATE_ACTIVITIES = "CREATE_ACTIVITIES";
export const SEARCH_COUNTRY = "SEARCH_COUNTRY";